#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

# Load trusted local configuration.
if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi

# Environment paths (override via env vars if needed)
LLM_ENV_PYTHON="${LLM_ENV_PYTHON:-$(command -v python)}"
SEG_ENV_PYTHON="${SEG_ENV_PYTHON:-$LLM_ENV_PYTHON}"
CLS_ENV_PYTHON="${CLS_ENV_PYTHON:-$LLM_ENV_PYTHON}"

# Service settings
HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-8003}"
LLM_MOCK="${LLM_MOCK:-0}"
LLM_MODEL_PATH="${LLM_MODEL_PATH:-$ROOT_DIR/models/Qwen3-VL-8B-Instruct}"
LLM_LORA_PATH="${LLM_LORA_PATH:-}"
LLM_DESCRIBE_ADAPTER="${LLM_DESCRIBE_ADAPTER:-dualhead}"
LLM_DUAL_HEAD_PATH="${LLM_DUAL_HEAD_PATH:-$ROOT_DIR/models/landslide_qwen3vl_dual_head_continuous_10ep_best}"
LLM_DUAL_HEAD_ADAPTER_ALWAYS_ON="${LLM_DUAL_HEAD_ADAPTER_ALWAYS_ON:-1}"
CLS_BACKEND="${CLS_BACKEND:-dualhead}"
LLM_DEFAULT_MAX_TOKENS="${LLM_DEFAULT_MAX_TOKENS:-1024}"
LLM_MAX_TOKENS_CAP="${LLM_MAX_TOKENS_CAP:-4096}"
LLM_REPORT_MAX_TOKENS="${LLM_REPORT_MAX_TOKENS:-3500}"
AGENT_ENABLE_REPORT_WRITE="${AGENT_ENABLE_REPORT_WRITE:-1}"
PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
SEG_ENABLE_LLM_SECOND_PASS="${SEG_ENABLE_LLM_SECOND_PASS:-0}"
SEG_LLM_SECOND_PASS_MAX_AREA_RATIO="${SEG_LLM_SECOND_PASS_MAX_AREA_RATIO:-0.20}"
OPENTOPOGRAPHY_API_KEY="${OPENTOPOGRAPHY_API_KEY:-}"
OPENTOPOGRAPHY_DEMTYPE="${OPENTOPOGRAPHY_DEMTYPE:-COP30}"
GEO_BACKGROUND_SLOPE_SAMPLE_METERS="${GEO_BACKGROUND_SLOPE_SAMPLE_METERS:-90}"
GEO_DEM_PROVIDER="${GEO_DEM_PROVIDER:-open-meteo}"
MMPRETRAIN_ROOT="${MMPRETRAIN_ROOT:-$ROOT_DIR/models/mmpretrain-main}"
CLS_CONFIG_PATH="${CLS_CONFIG_PATH:-$ROOT_DIR/models/mmpretrain-main/work_dirs/_debug_convnext_start/convnext-tiny_1xb16_landslide-50e.py}"
CLS_CHECKPOINT_PATH="${CLS_CHECKPOINT_PATH:-$ROOT_DIR/models/mmpretrain-main/work_dirs/_debug_convnext_start/best_accuracy_top1_epoch_45.pth}"
CLS_CLASS_MAPPING_PATH="${CLS_CLASS_MAPPING_PATH:-}"
CLS_DEVICE="${CLS_DEVICE:-cuda:0}"
CLS_FORCE_NO_WEIGHTS_ONLY_LOAD="${CLS_FORCE_NO_WEIGHTS_ONLY_LOAD:-1}"
OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
SEG_BACKEND="${SEG_BACKEND:-mmseg}"
MMSEG_CONFIG_PATH="${MMSEG_CONFIG_PATH:-$ROOT_DIR/models/mmsegmentation-main/work_dirs/segformer_mit-b2_1xb8-50e_landslide/segformer_mit-b2_1xb8-50e_landslide-binary-512x512.py}"
MMSEG_CHECKPOINT_PATH="${MMSEG_CHECKPOINT_PATH:-$ROOT_DIR/models/mmsegmentation-main/work_dirs/segformer_mit-b2_1xb8-50e_landslide/best_mIoU_epoch_28.pth}"
MMSEG_DEVICE="${MMSEG_DEVICE:-cuda:0}"
MMSEG_LANDSLIDE_CLASS_INDEX="${MMSEG_LANDSLIDE_CLASS_INDEX:-1}"
MMSEG_FOREGROUND_NONZERO="${MMSEG_FOREGROUND_NONZERO:-0}"
MMSEG_FORCE_NO_WEIGHTS_ONLY_LOAD="${MMSEG_FORCE_NO_WEIGHTS_ONLY_LOAD:-1}"

if ! [[ "$OMP_NUM_THREADS" =~ ^[0-9]+$ ]] || [[ "$OMP_NUM_THREADS" -lt 1 ]]; then
  OMP_NUM_THREADS=1
fi

if [[ ! -x "$LLM_ENV_PYTHON" ]]; then
  echo "Error: missing LLM python: $LLM_ENV_PYTHON"
  exit 1
fi
if [[ ! -x "$SEG_ENV_PYTHON" ]]; then
  echo "Warning: missing SEG python: $SEG_ENV_PYTHON"
  echo "         Segmentation service may fail to start from /admin/start_services."
fi
if [[ ! -x "$CLS_ENV_PYTHON" ]]; then
  echo "Warning: missing CLS python: $CLS_ENV_PYTHON"
  echo "         Classification service may fail to start from /admin/start_services."
fi

echo "Starting frontend server at http://${HOST}:${PORT}/"
echo "LLM_MOCK=${LLM_MOCK}"
echo "LLM_MODEL_PATH=${LLM_MODEL_PATH}"
echo "LLM_LORA_PATH=${LLM_LORA_PATH}"
echo "LLM_DESCRIBE_ADAPTER=${LLM_DESCRIBE_ADAPTER}"
echo "LLM_DUAL_HEAD_PATH=${LLM_DUAL_HEAD_PATH}"
echo "LLM_DUAL_HEAD_ADAPTER_ALWAYS_ON=${LLM_DUAL_HEAD_ADAPTER_ALWAYS_ON}"
echo "CLS_BACKEND=${CLS_BACKEND}"
echo "LLM_DEFAULT_MAX_TOKENS=${LLM_DEFAULT_MAX_TOKENS}"
echo "LLM_MAX_TOKENS_CAP=${LLM_MAX_TOKENS_CAP}"
echo "AGENT_ENABLE_REPORT_WRITE=${AGENT_ENABLE_REPORT_WRITE}"
echo "SEG_ENV_PYTHON=${SEG_ENV_PYTHON}"
echo "CLS_ENV_PYTHON=${CLS_ENV_PYTHON}"
echo "SEG_BACKEND=${SEG_BACKEND}"
echo "MMSEG_CONFIG_PATH=${MMSEG_CONFIG_PATH}"
echo "MMSEG_CHECKPOINT_PATH=${MMSEG_CHECKPOINT_PATH}"
echo "MMSEG_DEVICE=${MMSEG_DEVICE}"
echo "MMPRETRAIN_ROOT=${MMPRETRAIN_ROOT}"
echo "CLS_CONFIG_PATH=${CLS_CONFIG_PATH}"
echo "CLS_CHECKPOINT_PATH=${CLS_CHECKPOINT_PATH}"
echo "CLS_DEVICE=${CLS_DEVICE}"
echo "SEG_ENABLE_LLM_SECOND_PASS=${SEG_ENABLE_LLM_SECOND_PASS}"
echo "SEG_LLM_SECOND_PASS_MAX_AREA_RATIO=${SEG_LLM_SECOND_PASS_MAX_AREA_RATIO}"
echo "OPENTOPOGRAPHY_DEMTYPE=${OPENTOPOGRAPHY_DEMTYPE}"
echo "GEO_BACKGROUND_SLOPE_SAMPLE_METERS=${GEO_BACKGROUND_SLOPE_SAMPLE_METERS}"
echo "GEO_DEM_PROVIDER=${GEO_DEM_PROVIDER}"
echo "Model loads in background. Check /health for model_status=ready before first analysis."

exec env \
  LLM_ENV_PYTHON="$LLM_ENV_PYTHON" \
  LLM_MOCK="$LLM_MOCK" \
  LLM_MODEL_PATH="$LLM_MODEL_PATH" \
  LLM_LORA_PATH="$LLM_LORA_PATH" \
  LLM_DESCRIBE_ADAPTER="$LLM_DESCRIBE_ADAPTER" \
  LLM_DUAL_HEAD_PATH="$LLM_DUAL_HEAD_PATH" \
  LLM_DUAL_HEAD_ADAPTER_ALWAYS_ON="$LLM_DUAL_HEAD_ADAPTER_ALWAYS_ON" \
  CLS_BACKEND="$CLS_BACKEND" \
  LLM_DEFAULT_MAX_TOKENS="$LLM_DEFAULT_MAX_TOKENS" \
  LLM_MAX_TOKENS_CAP="$LLM_MAX_TOKENS_CAP" \
  LLM_REPORT_MAX_TOKENS="$LLM_REPORT_MAX_TOKENS" \
  AGENT_ENABLE_REPORT_WRITE="$AGENT_ENABLE_REPORT_WRITE" \
  PYTHONUNBUFFERED="$PYTHONUNBUFFERED" \
  SEG_ENABLE_LLM_SECOND_PASS="$SEG_ENABLE_LLM_SECOND_PASS" \
  OMP_NUM_THREADS="$OMP_NUM_THREADS" \
  SEG_ENV_PYTHON="$SEG_ENV_PYTHON" \
  CLS_ENV_PYTHON="$CLS_ENV_PYTHON" \
  SEG_BACKEND="$SEG_BACKEND" \
  MMSEG_CONFIG_PATH="$MMSEG_CONFIG_PATH" \
  MMSEG_CHECKPOINT_PATH="$MMSEG_CHECKPOINT_PATH" \
  MMSEG_DEVICE="$MMSEG_DEVICE" \
  MMSEG_LANDSLIDE_CLASS_INDEX="$MMSEG_LANDSLIDE_CLASS_INDEX" \
  MMSEG_FOREGROUND_NONZERO="$MMSEG_FOREGROUND_NONZERO" \
  MMSEG_FORCE_NO_WEIGHTS_ONLY_LOAD="$MMSEG_FORCE_NO_WEIGHTS_ONLY_LOAD" \
  MMPRETRAIN_ROOT="$MMPRETRAIN_ROOT" \
  CLS_CONFIG_PATH="$CLS_CONFIG_PATH" \
  CLS_CHECKPOINT_PATH="$CLS_CHECKPOINT_PATH" \
  CLS_CLASS_MAPPING_PATH="$CLS_CLASS_MAPPING_PATH" \
  CLS_DEVICE="$CLS_DEVICE" \
  CLS_FORCE_NO_WEIGHTS_ONLY_LOAD="$CLS_FORCE_NO_WEIGHTS_ONLY_LOAD" \
  SEG_LLM_SECOND_PASS_MAX_AREA_RATIO="$SEG_LLM_SECOND_PASS_MAX_AREA_RATIO" \
  OPENTOPOGRAPHY_API_KEY="$OPENTOPOGRAPHY_API_KEY" \
  OPENTOPOGRAPHY_DEMTYPE="$OPENTOPOGRAPHY_DEMTYPE" \
  GEO_BACKGROUND_SLOPE_SAMPLE_METERS="$GEO_BACKGROUND_SLOPE_SAMPLE_METERS" \
  GEO_DEM_PROVIDER="$GEO_DEM_PROVIDER" \
  "$LLM_ENV_PYTHON" -m uvicorn scripts.llm_service:app --host "$HOST" --port "$PORT"
